### ISSUE TITLE
1689 - Radares - ICMC USP.c

### ISSUE THREAD

**Issue by rodrigofegui** [luisarbezerra/URIJudgeOnline#1]
Este código foi considerado como resposta errada no URI.
Foi submetido desta forma e aceito ou houve um conserto?

**Comment by luisarbezerra** [comment]
> Este código foi considerado como resposta errada no URI.
> Foi submetido desta forma e aceito ou houve um conserto?

Olá,

Sim, o URI aceitou, inclusive conferi aqui.
